#!/bin/sh

file="$HOME/.phrases"
touch "$file"
height=$(wc -l "$file" | awk '{print $1}')
prompt="Add/delete a phrase: "
# add support of selecting clipboard

cmd=$(dmenu -l "$height" -p "$prompt" -nf white < "$file")

while [ -n "$cmd" ]; do
 	if grep -q "^$cmd\$" "$file"; then
		grep -v "^$cmd\$" "$file" > "$file.$$"
		mv "$file.$$" "$file"
        height=$(( height - 1 ))
 	else
		echo "$cmd" >> "$file"
		height=$(( height + 1 ))
 	fi

	cmd=$(dmenu -l "$height" -p "$prompt" "$@" < "$file")
done

exit 0
