#!/bin/sh

[ -f "$1" ] && cp "$1" ~/.config/wall.png && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed"

[ -d "$1" ] && cp `find "$1" -name "*.png" -o -name "*.jpg" -o -name "*.jpeg" -type f | shuf -n 1` ~/.config/wall.png # && notify-send -i "$HOME/.config/wall.png" "Wallpaper changed"

# if pywal is installed, use it.
# type wal >& /dev/null && {
#   wal -c 
#   wal -s -i ~/.config/wall.png -o ~/.config/wal/postrun 
#   xsetroot -name "fsignal:xrbd"
#   killall dwmblocks
#   setsid dwmblocks >/dev/null & } >& /dev/null


xwallpaper --zoom ~/.config/wall.png
