print("Hi Dumest Neovim User!")
require "user.plugins"
require "user.options"
require "user.keymaps"
require "user.colorscheme"
require "user.telescope"
require "user.gitsigns"
require "user.treesitter"
require "user.autopairs"
require "user.comment"
require "user.lualine-evil"
require "user.toggleterm"
require "user.project"
require "user.impatient"
require "user.indentline"
require "user.alpha"
require "user.whichkey"
require "user.autocommands"
require "user.code-runner"
-- require "user.peek" -- markdown preview
-- require "user.markdown-preview"
require "user.true-zen" -- for zen mode
require "user.vimtex"
require "user.surround"
require "user.colorizer"
require "user.colortils"
require "user.doc-color"
-- lsp completion snippets formatting
require "user.lsp"
require "user.cmp"
require "user.copilot"
require "user.neodev"
require "user.org-mode"
require "user.git-worktree"
require "user.commands"
require "user.dadbod" -- sql
require "user.nvim-tree"
require "user.hop"    -- easy motions
require "user.harpoon"
require "user.lazygit"
require "user.nvim-dap"
require "user.nvim-dap-ui"
require "user.nvim-dap-python"
require "user.obsidian"
-- require "user.auto-session"
require "user.icon-picker"
