#!/bin/sh
# reload sxhkd
## kill -SIGUSR1 < PID >

Print
  file_path=~/pics/scrs/$(/bin/date +%y-%m-%d_%H:%M:%S).png && maim -s $file_path && $IMAGE_VIEWER $file_path

control + Print 
  file_path=~/pics/scrs/$(/bin/date +%y-%m-%d_%H:%M:%S).png && maim $file_path && $IMAGE_VIEWER $file_path

# super + c 
#   nm-connection-editor
super + c
  wifi-con

super + w 
  brave-beta 

super + p 
  phrases

super + n 
  alacritty -e /usr/bin/nvim ~/t/rc.org

super + e 
  emacs ~/.emacs.org

super + t
  dmenu-translate -b

super + o
  todo

super + O
  obsidian

super + W
  whatsdesk

super + period; period
  dunstctl close
super + period; super period
  dunstctl close

super + period; {shift + c}
  dunstctl close-all

super + period; h
  dunstctl history-pop
