#!/bin/sh

# app images
alias obsidian="~/dows/Obsidian-1.2.8.AppImage"

alias p="sudo pacman"
alias ls='ls --color=auto'
alias j='z'
alias f='zi'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# ls 
alias ll="ls -l -h"
alias la "ls -l -h -a"

# config 
alias nvimrc='nvim ~/.config/nvim/'
alias zshrc='nvim ~/.config/zsh/'
alias rangerrc='nvim ~/.config/ranger/rc.conf'
alias lfrc='nvim ~/.config/lf/lfrc'
alias dwmfrc='cd ~/.config/dwm-flexipatch/'
alias dwmrc='cd ~/.config/dwm/'
alias zathurarc='nvim ~/.config/zathura/zathurarc'
alias alacrittyrc='nvim ~/.config/alacritty/alacritty.yml'
alias slrc='cd ~/.config/slstatus/ && nvim .'
alias sxrc='nvim ~/.config/sxhkd/sxhkdrc'
alias aliasrc='nvim ~/.config/zsh/zsh-aliases'
alias sxivrc="nvim ~/.config/sxiv/exec/key-handler"
## scripts
alias sc='cd ~/.local/bin'

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
# alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# brave-browser
alias brave='brave-nightly'

# alias for cisco linux cource
alias lnx='$BROWSER https://www.netacad.com/portal/learning'

# suspend or sleep the computer
alias go-sleep='systemctl suspend -i'

#	for neovim 
alias nv='nvim'

# convert from anything to pdf
alias topdf="soffice --headless --convert-to pdf "

# for shutdown now
alias sn="shutdown now"
