#!/bin/bash

## pacman and yay
alias i='yay -S'
alias u='yay -Syu'
alias r='yay -Rns'   # remove a package and its dependencies which are not required by any other installed package:
alias q='yay -Ss'
alias c='yay -Yc'

# xev 
alias xev="xev | awk -F'[ )]+' '/^KeyPress/ { a[NR+2] } NR in a { printf \"%-3s %s\n\", \$5, \$8 }'"

# chmod 
alias x="chmod +x"

# app images
# alias obsidian="~/apps/AppImages/Obsidian-1.4.13.AppImage"
alias ob="~/apps/AppImages/Obsidian-1.4.13.AppImage"
alias sxiv=nsxiv
alias xp="xppen"

alias cat="bat -n --pager less"
alias zz="z -"
alias cd="z"
alias vi='vim'
alias nv="$EDITOR"
alias nvn='~/apps/AppImages/nvim.appimage'
alias pnv="XDG_CONFIG_HOME=~/.config/$EDITOR.fresh XDG_DATA_HOME=~/.local/share/nvim.fresh XDG_STATE_HOME=~/.local/state/nvim.fresh nvim"
alias au="$EDITOR ~/.config/$EDITOR/lua/user/autocommands.lua"
alias zat="zathura"

alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

# ls 
alias ls='ls --color=auto'
alias ll="exa -l"
alias lll="exa -l -a"
alias tree="exa --tree"

# config 
alias nvrc="$EDITOR ~/.config/nvim/init.lua"
alias zshrc="$EDITOR ~/.config/zsh/"
alias rangerrc="$EDITOR ~/.config/ranger/rc.conf"
alias lfrc="$EDITOR ~/.config/lf/lfrc"
alias dwmfrc='cd ~/.config/dwm-flexipatch/'
alias dwmrc='cd ~/.config/dwm/'
alias dmrc='cd ~/.config/dmenu/'
alias zathurarc="$EDITOR ~/.config/zathura/zathurarc"
alias zathrc="$EDITOR ~/.config/zathura/zathurarc"
alias zarc="$EDITOR ~/.config/zathura/zathurarc"
alias alacrittyrc="$EDITOR ~/.config/alacritty/alacritty.yml"
alias slrc='cd ~/.config/slstatus/ && $EDITOR .'
alias sxrc="$EDITOR ~/.config/sxhkd/sxhkdrc"
alias aliasrc="$EDITOR ~/.config/zsh/zsh-aliases"
alias alrc="$EDITOR ~/.config/zsh/zsh-aliases"
alias al="$EDITOR ~/.config/zsh/zsh-aliases"
alias sxivrc="$EDITOR ~/.config/nsxiv/exec/key-handler"
alias nsxivrc="$EDITOR ~/.config/nsxiv/exec/key-handler"
alias picomrc="$EDITOR ~/.config/picom.conf"
alias tmuxrc="$EDITOR ~/.tmux.conf"
alias xres="$EDITOR ~/.Xresources"
alias cmrc="$EDITOR ~/.config/zsh/zsh-commands"


## scripts
# alias sc='cd ~/.local/scripts'   # use sc as a fzf

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
# alias rm='rm -i'

# easier to read disk
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# systemd
alias list_systemctl="systemctl list-unit-files --state=enabled"

# brave-browser
alias brave='brave-beta'

# learning 
alias lnx='$BROWSER https://www.netacad.com/portal/learning'
alias nt='$BROWSER "https://skillsforall.com/launch?id=f393c38f-b410-4d2b-8275-70e144273519&tab=curriculum&view=79932ede-7bba-57ef-a312-ac4d72c37c84"'
alias drive='$BROWSER https://drive.google.com/drive/my-drive'
alias email='$BROWSER https://mail.google.com/mail/u/0'
alias swm='$BROWSER https://www.youtube.com/watch?v=382OExOIipQ&t=3354s'

# suspend or sleep the computer
alias go-sleep='systemctl suspend -i'


# co$EDITORert from anything to pdf
alias topdf="soffice --headless --co$EDITORert-to pdf "

# for shutdown now
alias sn="shutdown now"

# xppen config app
alias xppen="~/apps/xppen_tablet/XPPenLinux3.4.6-230714/App/usr/lib/pentablet/PenTablet.sh"
