#!/bin/sh

# Example for $XDG_CONFIG_HOME/sxiv/exec/key-handler
# Called by sxiv(1) after the external prefix key (C-x by default) is pressed.
# The next key combo is passed as its first argument. Passed via stdin are the
# images to act upon, one path per line: all marked images, if in thumbnail
# mode and at least one image has been marked, otherwise the current image.
# sxiv(1) blocks until this script terminates. It then checks which images
# have been modified and reloads them.

# The key combo argument has the following form: "[C-][M-][S-]KEY",
# where C/M/S indicate Ctrl/Meta(Alt)/Shift modifier states and KEY is the X
# keysym as listed in /usr/include/X11/keysymdef.h without the "XK_" prefix.

rotate() {
	degree="$1"
	tr '\n' '\0' | xargs -0 realpath | sort | uniq | while read file; do
		case "$(file -b -i "$file")" in
		image/jpeg*) jpegtran -rotate "$degree" -copy all -outfile "$file" "$file" ;;
		*)           mogrify  -rotate "$degree" "$file" ;;
		esac
	done
}

# case "$1" in
# "C-x")      xclip -in -filter | tr '\n' ' ' | xclip -in -selection clipboard ;;
# "C-c")      while read file; do xclip -selection clipboard -target image/png "$file"; done ;;
# "C-e")      while read file; do urxvt -bg "#444" -fg "#eee" -sl 0 -title "$file" -e sh -c "exiv2 pr -q -pa '$file' | less" & done ;;
# "C-g")      tr '\n' '\0' | xargs -0 gimp & ;;
# # "C-r")      while read file; do rawtherapee "$file" & done ;;
# "C-comma")  rotate 270 ;;
# "C-period") rotate  90 ;;
# "C-slash")  rotate 180 ;;
# "C-r") 
#   name="$(dmenu -p "rename $file to: ")" 2> /dev/null
#   if ! [ -z "$name" ]; then
#     notify-send "hi"
#   fi
# ;;
# esac


while read file
do
  case "$1" in
    "C-d")
      notify-send "Deleted: $file"
      gio trash "$file" 
      ;;
    "C-m")
      alacritty --class centered -e sxivfzfmv "$file"
      ;;
    "C-c")
      echo -n "$file" | xclip -selection clipboard ;;
    "C-r") 
      name="$(dmenu -p "rename $file to: " 2> /dev/null)"
      if ! [ -z "$name" ]; then
        # Extract the file's extension
        extension="${file##*.}"
        # Extract the directory path
        directory="$(dirname "$file")"
        # Rename the file with the new filename and the original extension
        mv "$file" "$directory/$name.$extension"
        notify-send "Renamed: $file to $directory/$name.$extension"
      fi
      # alacritty  --class spterm -e ranger ~/pics/scrs/
      ;;
    # rotate 90 degrees clockwise to Shift + r
    "S-r")
      rotate 90
      ;;
    # mv the file to ~/docs/Vaults Obsidian/imgs 
    "C-o")
      name="$(dmenu -p "rename $file to: " 2> /dev/null)"
      if ! [ -z "$name" ]; then
      # Extract the file's extension
      extension="${file##*.}"
      # Extract the directory path
      directory="$(dirname "$file")"
      # Rename the file with the new filename and the original extension
      mv "$file" "$VAULT/imgs/$name.$extension"
      notify-send "Moved: $file to $VAULT/imgs/$name.$extension"
      fi
      ;;
    '[')
      sxiv -z -0.1
      ;;
    ']')
      sxiv -z 0.1
      ;;

    # open image with annotator
    "C-a")
      notify-send "Annotated: $file"
      annotator "$file"
      ;;

  esac
done
# zoom in with ] and out with [
case "$1" in
  *)
    exit 2 
    ;;
esac
